# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulse" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "e68675ed53b6f5e1d03b403fe3546277c6a725de3f760a507a52540d1a5c5644"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b790a07f7666ee2254263eff82d547b37ea45dc5a570ce02926a6225cb65dc47"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60deac12ea0f6fa6cd87c1829aea0d016ecc8ecf7c8a41eef04d0d645f58f792"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "75275fca3eb8f3830c06d00300fa1a08c42e9c977db123de8934fd58b01d271c"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pulse"
  desc "Pulse — Sovera Markdown↔Confluence sync CLI"
  homepage "https://github.com/sovera-dev/sovera-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulse"
  bash_completion "completions/pulse.bash"
  fish_completion "completions/pulse.fish"
  zsh_completion "completions/pulse.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pulse"]
    end
  end

  # No zap stanza required

end
