# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulse" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "103805a23625e4df1be2a03adfe624ed11d9b6b1f6734ca822422b021397cf96"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf76879ee6efbd6a2e63c14c9fcb15ff1e6545cf8dc71aa60aca6f7bc6935959"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de396b347707aad8ebc5ed7b41df84bb33ed14c9f024bef9b4128fad84ce5ef0"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "546034acca71e650e836d455e671599bf7121e95ae8374a36b74354849d58ace"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pulse"
  desc "Pulse — Sovera Markdown↔Confluence sync CLI"
  homepage "https://github.com/sovera-dev/sovera-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulse"
  bash_completion "completions/pulse.bash"
  fish_completion "completions/pulse.fish"
  zsh_completion "completions/pulse.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pulse"]
    end
  end

  # No zap stanza required

end
