# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulse" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "a30a95d17bdca808b2b58f0987f8a3dbc48c9ba36f49300024a80aea2ee9ad4a"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "29c18ae62a05a9a7ab442ed4b15fa835fa5fd090e67c3fe5feceff42a306a6df"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "714d2363acb6bc3ce7aac3a79474f49f6f253ae0f1cb637c0d452aa7cceeb643"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c92d75f8b91d401acf28b9ec87d701bf53745d79c738498582555aab27eaaba9"
      url "https://github.com/sovera-dev/sovera-toolkit/releases/download/v#{version}/pulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pulse"
  desc "Pulse — Sovera Markdown↔Confluence sync CLI"
  homepage "https://github.com/sovera-dev/sovera-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulse"
  bash_completion "completions/pulse.bash"
  fish_completion "completions/pulse.fish"
  zsh_completion "completions/pulse.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pulse"]
    end
  end

  # No zap stanza required

end
